In [4]:
import numpy as np

In [5]:
L = np.random.random(100)
sum(L)

np.float64(51.95576052528417)

In [6]:
np.sum(L)   

np.float64(51.95576052528416)

In [7]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

106 ms ± 12.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.38 ms ± 42.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
min(big_array), max(big_array)

(np.float64(1.7004571895018472e-07), np.float64(0.9999997846282209))

In [9]:
%timeit min(big_array)
%timeit np.min(big_array)

56.1 ms ± 8.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
529 μs ± 19.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
M = np.random.random((3, 4))
print(M)
M.sum()

[[0.96005394 0.05014772 0.25069049 0.81245126]
 [0.49082526 0.19954105 0.76727825 0.41153068]
 [0.17831522 0.65318527 0.86336765 0.73409463]]


np.float64(6.3714814322589355)

In [11]:
M.min(axis=0)
M.max(axis=1)

array([0.96005394, 0.76727825, 0.86336765])