In [1]:
import numpy as np

In [2]:
arr = np.array([10 , 20 , 30 , 40 , 50])
indices = [0, 2, 4]
arr[indices]

array([10, 30, 50])

In [ ]:
arr2d = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]])

rows = [0, 2]  
cols = [1, 2]  

print(arr2d[rows, :])   
print(arr2d[:, cols])   
print(arr2d[rows, cols])

[[10 20 30]
 [70 80 90]]
[[20 30]
 [50 60]
 [80 90]]
[20 90]


In [4]:
arr = np.array([10, 20, 30, 40, 50])
maks = arr > 25
print(arr[maks])

[30 40 50]


In [5]:
rows = np.array([0, 2])
cols = np.array([1, 2])

print(arr2d[np.ix_(rows, cols)])

[[20 30]
 [80 90]]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[[1, 3]] = 99  # Change elements at index 1 and 3 to 99

print(arr)

[10 99 30 99 50]
