In [1]:
import numpy as np

In [3]:
A = np.array([3, 7, 2, 5, 6, 3, 5, 4])
A > 5

array([False,  True, False, False,  True, False, False, False])

In [4]:
mask = A > 5
filtered_A = A[mask]
filtered_A

array([7, 6])

In [ ]:
A != 4 #checks if A is not equal to 4
A <= 7  #checks if A is less than or equal to 7

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [6]:
# Elements greater than 2 AND less than 8
print(A[(A > 2) & (A < 8)])

# Elements that are either 3 or 9
print(A[(A == 3) | (A == 9)])

# Invert the condition (NOT greater than 5)
print(A[~(A > 5)])


[3 7 5 6 3 5 4]
[3 3]
[3 2 5 3 5 4]


In [7]:
result = np.where(A > 5, 100, 0)
print(result)

[  0 100   0   0 100   0   0   0]


In [8]:
count = np.sum(A > 5)  # Count elements greater than 5
print(count)

2


In [9]:
print(np.any(A > 8))  # Check if any element > 8
print(np.all(A > 2))  # Check if all elements > 2

False
False


In [10]:
indices = np.nonzero(A > 5)
print(indices)

(array([1, 4]),)


In [11]:
B = np.array([[1, 5, 8], 
              [3, 7, 2], 
              [9, 4, 6]])

# Get values greater than 5
print(B[B > 5])

[8 7 9 6]


In [ ]:
B[B < 5] = 0
print(B)