In [1]:
import numpy as np

arr = np.array([3, 1, 5, 2, 4])
sorted_arr = np.sort(arr)  # Ascending order
sorted_arr_desc = np.sort(arr)[::-1]  # Descending order

print(sorted_arr)        
print(sorted_arr_desc)   

[1 2 3 4 5]
[5 4 3 2 1]


In [2]:
arr = np.array([3, 1, 5, 2, 4])
sorted_indices = np.argsort(arr)

print(sorted_indices)    
print(arr[sorted_indices]) 

[1 3 0 4 2]
[1 2 3 4 5]


In [3]:
matrix = np.array([[3, 2, 1], [6, 5, 4]])
sorted_matrix = np.sort(matrix, axis=1)  # Sort each row

print(sorted_matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
import time

arr = np.random.randint(0, 10000, 10**6)  # Large array with 1 million elements

for algo in ["quicksort", "mergesort", "heapsort", "stable"]:
    start = time.time()
    np.sort(arr, kind=algo)
    end = time.time()
    print(f"{algo}: {end - start:.5f} seconds")
